export const LIST_ALL = 'LIST_ALL'
export const SAVE_TASK = 'SAVE_TASK'
export const DISPLAY_FORM = 'DISPLAY_FORM'
export const TOGGLE_FORM = 'TOGGLE_FORM'
export const CLOSE_FORM = 'CLOSE_FORM'
export const UPDATE_STATUS = 'UPDATE_STATUS'
export const DELETE = 'DELETE'
export const EDIT = 'EDIT'